Aaron Broderick <br>
443-538-7284 <br>
aaronbroderickpiano@gmail.com <br>
<br>
Coding challenge for VarenTech 4-13-2018

In [1]:
import pandas as pd

In [2]:
def get_scores(string):
    
    # Make a string into a list of 10 strings, representing frames.  
    
    frame_count = 0
    frames = []
    string = string.replace('-','0')
    z = list(string)
    
    while frame_count < 9:
        if z[0] == 'X':
            frames.append(z.pop(0))
            frame_count += 1
        else:
            x = z.pop(0) + z.pop(0)
            frames.append(x)
            frame_count += 1 
    frames.append(''.join(z))
    
    x = frames
    
    # Let's go bowling!
    
    score = []
    
    for i in range(0,10):
        frame_score = 0
        
        # Frame 10
        
        if i == 9:
            final = list(x[9])
            for i in range(len(final)):
                if final[i] == 'X':
                    frame_score += 10
                elif final[i] == '/':
                    frame_score += 10 - int(final[i - 1])
                else:
                    frame_score += int(final[i])
            score.append(frame_score)
            
        # Frames 1-9
        
        else:
            # What to do if you have a strike.
            
            if x[i] == 'X':
                frame_score += 10
                
                # If it is the 9th frame.
                
                if i == 8:
                    if x[i + 1][0] == 'X':
                        frame_score += 10
                        if x[i + 1][1] == 'X':
                            frame_score += 10
                            score.append(frame_score)
                        else:
                            frame_score += int(x[i + 1][1])
                            score.append(frame_score)
                    elif '/' in x[i + 1] == True:
                        frame_score += 10
                        score.append(frame_score)
                    else:
                        frame_score += int(x[i + 1][0]) + int(x[i + 1][1])
                        score.append(frame_score)
                        
                # Frames 1-8
                
                else:        
                    if x[i + 1][0].isdigit() and x[i + 1][1].isdigit() == True:
                        frame_score += int(x[i+1][0]) + int(x[i+1][1])
                        score.append(frame_score)
                    elif '/' in x[i + 1]:
                        frame_score += 10
                        score.append(frame_score)
                    elif 'X' in x[i + 1]:
                        frame_score += 10
                        if x[i + 2][0] == 'X':
                            frame_score += 10
                            score.append(frame_score)
                        else:
                            frame_score += int(x[i + 2][0])
                            score.append(frame_score)
                            
            # What to do if you have a spare
            
            elif '/' in x[i]:
                frame_score += 10
                if x[i + 1] == 'X':
                    frame_score += 10
                    score.append(frame_score)
                else:
                    frame_score += int(x[i + 1][0])
                    score.append(frame_score)
            
            # What to do otherwise
            
            else:
                frame_score += int(x[i][0]) + int(x[i][1])
                score.append(frame_score)
                
    return(sum(score))

In [3]:
# Test cases

a = 'XXXXXXXXXXXX'
b = '9-9-9-9-9-9-9-9-9-9-'
c = '5/5/5/5/5/5/5/5/5/5/5'
d = 'X7/9-X-88/-6XXX81'

df = pd.DataFrame()
df['bowling_strings'] = [a,b,c,d]
df['expected_scores'] = [300, 90, 150, 167]
df

         bowling_strings  expected_scores
0           XXXXXXXXXXXX              300
1   9-9-9-9-9-9-9-9-9-9-               90
2  5/5/5/5/5/5/5/5/5/5/5              150
3      X7/9-X-88/-6XXX81              167

In [4]:
scores = []

for i in range(len(df.bowling_strings)):
    scores.append(get_scores(df.bowling_strings[i]))

df['computed_scores'] = scores
df

         bowling_strings  expected_scores  computed_scores
0           XXXXXXXXXXXX              300              300
1   9-9-9-9-9-9-9-9-9-9-               90               90
2  5/5/5/5/5/5/5/5/5/5/5              150              150
3      X7/9-X-88/-6XXX81              167              167